[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin123') if not User.objects.filter(username='admin').exists() else print('User exists')\" && gunicorn config.wsgi --log-file -"
