# Generated by Django 5.1.4 on 2025-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doc_type", models.CharField(max_length=50, verbose_name="DocType")),
                ("doc_num", models.CharField(max_length=50, verbose_name="DocNum")),
                ("accounting_date", models.DateField(verbose_name="Date comptable")),
                (
                    "payment_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Payment HT"
                    ),
                ),
                (
                    "payment_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Payement TTC"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Méthode de paiement"),
                ),
                (
                    "project_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Code projet"
                    ),
                ),
                (
                    "num",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Num"
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Total"
                    ),
                ),
                ("dat", models.DateField(blank=True, null=True, verbose_name="Dat")),
                ("canceled", models.CharField(max_length=1, verbose_name="Canceled")),
                (
                    "accompte_flag",
                    models.CharField(max_length=1, verbose_name="Accompte_Flag"),
                ),
            ],
            options={
                "verbose_name": "Avancement",
                "verbose_name_plural": "Avancements",
                "indexes": [
                    models.Index(
                        fields=["project_code"], name="facturation_project_dbd76d_idx"
                    ),
                    models.Index(
                        fields=["accounting_date"],
                        name="facturation_account_de4647_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Facturation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Numéro de document"),
                ),
                (
                    "registration_date",
                    models.DateField(verbose_name="Date d'enregistrement"),
                ),
                (
                    "document_status",
                    models.CharField(max_length=10, verbose_name="Statut document"),
                ),
                (
                    "client_code",
                    models.CharField(
                        max_length=50, verbose_name="Code client/fournisseur"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom du client/fournisseur"
                    ),
                ),
                ("item_code", models.CharField(max_length=50, verbose_name="ItemCode")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Price"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="LineTotal"
                    ),
                ),
                (
                    "total_after_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Total après remise",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Code projet"
                    ),
                ),
            ],
            options={
                "verbose_name": "Facturation",
                "verbose_name_plural": "Facturations",
                "indexes": [
                    models.Index(
                        fields=["project_code"], name="facturation_project_62ba58_idx"
                    ),
                    models.Index(
                        fields=["registration_date"],
                        name="facturation_registr_933f1e_idx",
                    ),
                ],
            },
        ),
    ]
