# Generated by Django 5.1.4 on 2025-02-19 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_delete_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_projects_created", models.PositiveIntegerField(default=0)),
                (
                    "total_project_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="User's department",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="User's job title",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="User's contact number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
