# Generated by Django 5.1.4 on 2025-02-13 11:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControleDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "numero_article",
                    models.CharField(
                        db_index=True,
                        help_text="Article number (unique identifier)",
                        max_length=50,
                    ),
                ),
                (
                    "code_projet",
                    models.CharField(
                        db_index=True,
                        help_text="Project code from related commandes",
                        max_length=50,
                    ),
                ),
                (
                    "type_projet",
                    models.CharField(
                        choices=[("FORFAIT", "Forfait"), ("METRE", "Métré")],
                        default="FORFAIT",
                        help_text="Project type (Forfait or Maître d'oeuvre)",
                        max_length=10,
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base selling price for METRE, standard price for FORFAIT",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "prix_vente_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Landing selling price (only for METRE projects)",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "budget_chef_projet",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base project manager budget for METRE, standard budget for FORFAIT",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "budget_chef_projet_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Landing project manager budget (only for METRE projects)",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "reste_a_depenser",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining amount to spend (manual input)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "fiabilite",
                    models.CharField(
                        blank=True,
                        choices=[("E", "Estimé"), ("C", "Chiffré"), ("M", "Marché")],
                        help_text="Reliability level (Estimé, Chiffré, Marché)",
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrôle des dépenses",
                "verbose_name_plural": "Contrôles des dépenses",
                "indexes": [
                    models.Index(
                        fields=["numero_article"], name="controle_de_numero__bfb67a_idx"
                    ),
                    models.Index(
                        fields=["code_projet"], name="controle_de_code_pr_87b34b_idx"
                    ),
                ],
                "unique_together": {("numero_article", "code_projet")},
            },
        ),
    ]
